### ISSUE TITLE
Ruby/Sequel extension?

### ISSUE THREAD

**Issue by ddebernardy** [jeff-davis/PostgreSQL-Temporal#2]
I noticed you were active on ruby-related projects. Might you be aware of a ruby/sequel extension that would allow to make use of the Postgres type?

**Comment by jeff-davis** [comment]
I'd very much like support in Sequel for temporal/range types.

It might be a good idea to wait a little to see how range types turn out. That might act as more of a standard because it will be supported and tested by the community; so it would be a better foundation on which to build higher-level support.
